version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3,lambda,logs
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test-aws-access-key
      - AWS_SECRET_ACCESS_KEY=test-aws-secret-key
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./create-resources.sh:/docker-entrypoint-initaws.d/create-resources.sh
